### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by yashovardhanagrawal** [Addy-Smart-Addresses/Addy-Android#4]
**I'm submitting a ...**
- [x] feature request

Improve our README file.

**Steps to reproduce:**
you may mention our gitter channel link https://gitter.im/Addy-Smart-Addresses

**Comment by codeteo** [comment]
I have also made some changes to `README.md` to display the logo. Check PR #6

**Comment by codeteo** [comment]
I can change the size so the logo will be like [this](https://github.com/Addy-Smart-Addresses/Addy/blob/master/README.md). Cause right now it's just a link and there's no logo displayed. Just re-open #6 so I can push it there.

**Comment by yashovardhanagrawal** [comment]
@codeteo just create a new PR, it would be better I guess.
